server:
  listen: 8080
  workers: 4

  upstreams:
    - id: node1
      url: https://jsonplaceholder.typicode.com
    - id: node2
      url: http://localhost:8002

  headers:
    - key: x-forwarded-for
      value: '$ip'
    - key: Authorization
      value: 'Bearer xyz'

  rules:
    - path: "/admin"
      match: "^/admin($|/.*)"  # Regex for `/admin` and any sub-path
      upstreams:
        - node2
    - path: "/todos"
      match: "^/todos($|/.*)"  # Regex for `/todos` and any sub-path
      upstreams:
        - node1
    - path: "/"
      match: ".*"  # Matches any path
      upstreams:
        - node1
        - node2
